local staticHeads = {
	-- ["DynamicHeadName"] = "rbxassetid://ClassicFaceID"
	["https://assetdelivery.roblox.com/v1/asset/?id=14366112499"] = "rbxasset://textures/face.png", -- Default Smile (Stevie Standard)
	["https://assetdelivery.roblox.com/v1/asset/?id=13020957350"] = "rbxasset://textures/face.png", -- Default Smile (Dylan Default)
	["https://assetdelivery.roblox.com/v1/asset/?id=13021695400"] = "rbxasset://textures/face.png", -- Default Smile (Devon Default)
	["https://assetdelivery.roblox.com/v1/asset/?id=16041838499"] = "rbxassetid://7317606", -- Good Intentioned
	["https://assetdelivery.roblox.com/v1/asset/?id=15093418869"] = "rbxassetid://14861556", -- :P
	["https://assetdelivery.roblox.com/v1/asset/?id=10704977958"] = "rbxassetid://7074780", -- Check It
	["https://assetdelivery.roblox.com/v1/asset/?id=11445572546"] = "rbxassetid://7074780", -- Check It (R15)
	["https://assetdelivery.roblox.com/v1/asset/?id=13691524922"] = "rbxassetid://616394568", -- Friendly Smile
	["https://assetdelivery.roblox.com/v1/asset/?id=14377320953"] = "rbxassetid://616395480", -- The Winning Smile
	["https://assetdelivery.roblox.com/v1/asset/?id=14719225657"] = "rbxassetid://15431991", -- :3
	["https://assetdelivery.roblox.com/v1/asset/?id=12929417417"] = "rbxassetid://31117192", -- Skeptic
	["https://assetdelivery.roblox.com/v1/asset/?id=12939016971"] = "rbxassetid://26424652", -- Know it All Grin
	["https://assetdelivery.roblox.com/v1/asset/?id=12937016609"] = "rbxassetid://18151722", -- :]
	["https://assetdelivery.roblox.com/v1/asset/?id=10998132528"] = "rbxassetid://3994344171", -- Classic Male Face
	["https://assetdelivery.roblox.com/v1/asset/?id=13821294344"] = "rbxassetid://15637705", -- -_-
	["https://assetdelivery.roblox.com/v1/asset/?id=12945364777"] = "rbxassetid://30394483", -- Braces
	["https://assetdelivery.roblox.com/v1/asset/?id=13820802344"] = "rbxassetid://168332209", -- Not Sure if...
	["https://assetdelivery.roblox.com/v1/asset/?id=13675436366"] = "rbxassetid://29532362", -- Vampire
	["https://assetdelivery.roblox.com/v1/asset/?id=13674780763"] = "rbxassetid://7074882", -- Drool
	["https://assetdelivery.roblox.com/v1/asset/?id=14637766494"] = "rbxassetid://16132434", -- :D
	["https://assetdelivery.roblox.com/v1/asset/?id=14521518488"] = "rbxassetid://7074749", -- Chill
	["https://assetdelivery.roblox.com/v1/asset/?id=13684434516"] = "rbxassetid://8560915", -- Stare
	["https://assetdelivery.roblox.com/v1/asset/?id=14840473015"] = "rbxassetid://28999175", -- Joyous Surprise
	["https://assetdelivery.roblox.com/v1/asset/?id=14193224583"] = "rbxassetid://15365479", -- ^-^
	["https://assetdelivery.roblox.com/v1/asset/?id=12860895688"] = "rbxassetid://20418518", -- Err...
	["https://assetdelivery.roblox.com/v1/asset/?id=12945457988"] = "rbxassetid://20010294", -- Yawn
	["https://assetdelivery.roblox.com/v1/asset/?id=14374802942"] = "rbxassetid://28999175", -- Joyous Smile
	["https://assetdelivery.roblox.com/v1/asset/?id=14719266373"] = "rbxassetid://15324447", -- >_<
	["https://assetdelivery.roblox.com/v1/asset/?id=13692882504"] = "rbxassetid://10749456", -- Finn McCool
	["https://assetdelivery.roblox.com/v1/asset/?id=14192299483"] = "rbxassetid://12466911", -- Ghost Face
	["https://assetdelivery.roblox.com/v1/asset/?id=13684480556"] = "rbxassetid://209715003", -- Suspicious
	["https://assetdelivery.roblox.com/v1/asset/?id=11116786674"] = "rbxassetid://3994345447", -- Classic Female Face
	["https://assetdelivery.roblox.com/v1/asset/?id=14367119766"] = "rbxassetid://22877631", -- Whistle
	["https://assetdelivery.roblox.com/v1/asset/?id=14918993907"] = "rbxassetid://12145059", -- Freckles
	["https://assetdelivery.roblox.com/v1/asset/?id=13675155984"] = "rbxassetid://2222767231", -- Hold It In
	["https://assetdelivery.roblox.com/v1/asset/?id=13702851678"] = "rbxassetid://416829065", -- Anime Surprise
	["https://assetdelivery.roblox.com/v1/asset/?id=14638203853"] = "rbxassetid://21635489", -- Heeeeeey...
	["https://assetdelivery.roblox.com/v1/asset/?id=13823226706"] = "rbxassetid://32723156", -- I <3 New Site Theme
	["https://assetdelivery.roblox.com/v1/asset/?id=13822585823"] = "rbxassetid://150070505", -- Huh?
	["https://assetdelivery.roblox.com/v1/asset/?id=14640105786"] = "rbxassetid://32058103", -- So Funny
	["https://assetdelivery.roblox.com/v1/asset/?id=14695685417"] = "rbxassetid://10749463", -- Dizzy Face
	["https://assetdelivery.roblox.com/v1/asset/?id=14719366846"] = "rbxassetid://7074856", -- Winky
	["https://assetdelivery.roblox.com/v1/asset/?id=14401306473"] = "rbxassetid://25165947", -- Squiggle Mouth
	["https://assetdelivery.roblox.com/v1/asset/?id=14524488089"] = "rbxassetid://7506025", -- It's Go Time!
	["https://assetdelivery.roblox.com/v1/asset/?id=14760102190"] = "rbxassetid://19398553", -- Grr!
	["https://assetdelivery.roblox.com/v1/asset/?id=14192828782"] = "rbxassetid://14030506", -- I Hate Noobs
	["https://assetdelivery.roblox.com/v1/asset/?id=13684329978"] = "rbxassetid://15470573", -- Hut Hut Hike!
	["https://assetdelivery.roblox.com/v1/asset/?id=14205146154"] = "rbxassetid://49045252", -- Monster Face
	["https://assetdelivery.roblox.com/v1/asset/?id=14760226358"] = "rbxassetid://8329438", -- Stich Face
	["https://assetdelivery.roblox.com/v1/asset/?id=14754581557"] = "rbxassetid://7317591", -- Slick Fang
	["https://assetdelivery.roblox.com/v1/asset/?id=14638467750"] = "rbxassetid://405704879", -- ROAR!!!
	["https://assetdelivery.roblox.com/v1/asset/?id=14701679873"] = "rbxassetid://8329434", -- Sinister
	["https://assetdelivery.roblox.com/v1/asset/?id=14193020364"] = "rbxassetid://7075459", -- :-/
	["https://assetdelivery.roblox.com/v1/asset/?id=14525129330"] = "rbxassetid://15885042", -- Cutiemouse
	["https://assetdelivery.roblox.com/v1/asset/?id=12937135097"] = "rbxassetid://226216895", -- Lauging Fun
	["https://assetdelivery.roblox.com/v1/asset/?id=14192630651"] = "rbxassetid://14516479", -- Sniffles
	["https://assetdelivery.roblox.com/v1/asset/?id=14205179825"] = "rbxassetid://7317691", -- :-O
	["https://assetdelivery.roblox.com/v1/asset/?id=14193703522"] = "rbxassetid://629933140", -- Big Sad Eyes
	["https://assetdelivery.roblox.com/v1/asset/?id=13691867290"] = "rbxassetid://20298933", -- Puck
	["https://assetdelivery.roblox.com/v1/asset/?id=15938884849"] = "rbxassetid://7699086", -- Silly Fun
	["https://assetdelivery.roblox.com/v1/asset/?id=87462188394361"] = "rbxassetid://25321744", -- Friendly Grin
	["https://assetdelivery.roblox.com/v1/asset/?id=15381465917"] = "rbxassetid://7075492", -- Lazy Eye
	["https://assetdelivery.roblox.com/v1/asset/?id=16042016783"] = "rbxassetid://236455674", -- Happy Wink
	["https://assetdelivery.roblox.com/v1/asset/?id=15555752896"] = "rbxassetid://7074712", -- Glee
	["https://assetdelivery.roblox.com/v1/asset/?id=15554828524"] = "rbxassetid://20722053", -- Shiny Teeth
	["https://assetdelivery.roblox.com/v1/asset/?id=15381387290"] = "rbxassetid://23931977", -- Awkward
	["rbxassetid://72686050792671"] = "rbxassetid://42070872", -- Epic Face (fragmented robloxian)
	["rbxassetid://105166641643904"] = "rbxassetid://83022608", -- Woman Face
	["rbxassetid://73858495768741"] = "rbxassetid://83017053", -- Man Face
}

return staticHeads
